### ISSUE TITLE
文章内部锚点无法跳转

### ISSUE THREAD

**Issue by bailicangdu** [raoenhui/next-site-cn#1]
比如这样的锚点
![image](https://user-images.githubusercontent.com/20297227/48488718-5e358080-e85c-11e8-83b2-920fb3e60b97.png)

**Comment by raoenhui** [comment]
谢谢提的意见，我会尽快修复的😁

**Comment by raoenhui** [comment]
已经修复 @bailicangdu [http://nextjs.frontendx.cn](http://nextjs.frontendx.cn)

**Comment by bailicangdu** [comment]
辛苦辛苦👍

**Comment by raoenhui** [comment]
😁谢谢大佬支持
