### ISSUE TITLE
关于postcss-pxtorem

### ISSUE THREAD

**Issue by MicoinSmith** [raoenhui/next-site-cn#4]
hello 您知道nextjs 中 post-pxtorem 怎么配置吗， 我配置后没法设置html 中根元素 font-size 大小，也就没法自定义 postcss-pxtorem 中rootValue 了 有什么解决办法吗~ 
谢谢~

**Comment by 1111mp** [comment]
@MicoinSmith 我也遇到了 请问解决了吗

**Comment by raoenhui** [comment]
本仓库暂时只接受翻译问题。其他用法建议往https://github.com/zeit/next.js/issues提。
