### ISSUE TITLE
使用postcss-loader出现的问题！！！！

### ISSUE THREAD

**Issue by 1111mp** [raoenhui/next-site-cn#5]
我的postcss-config.js
`const autoprefixer = require('autoprefixer');
const pxtorem = require('postcss-pxtorem');

module.exports = {
  plugins: [
    autoprefixer({
      overrideBrowserslist: ['> 1%', 'last 4 versions'],
    }),
    pxtorem({
      rootValue: 70,
      unitPrecision: 5,
      propList: ["*"],
      selectorBlackList: [/^.nop2r/, /^.am/],
      replace: true,
      mediaQuery: false,
      minPixelValue: 0
    })
  ],
};`
next.config.js
`const withCSS = require('@zeit/next-css')
module.exports = withCSS()
const withSass = require('@zeit/next-sass')
module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  }
})`
出现的问题如下：
我给一个h1标签设置字体大小`h1 {
  display: flex;
  flex: 1;
  font-size: 20px;
  width: 70px;
}`
但是在浏览器显示：

**Comment by 1111mp** [comment]
上传不了图片 我就描述一下了 
在浏览器控制台查看样式 h1的样式如下`    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    font-size: 0.28571rem;
    width: 1rem;`
但是在查看计算之后的样式（computed）`font-size:12px;width:16px;`

**Comment by 1111mp** [comment]
请问这是什么问题呢 有解决方法吗

**Comment by raoenhui** [comment]
本仓库暂时只接受翻译问题。其他用法建议往https://github.com/zeit/next.js/issues提
