### ISSUE TITLE
请教一下，关于showcase界面图片加载过度的实现

### ISSUE THREAD

**Issue by dongchaoge** [raoenhui/next-site-cn#7]
您好，想请教一下showcase使用svg画出过度图片是怎么实现的。
就是就showcase-manifest.js这个文件下面的mapping下面的data字段的值是怎么计算出来的。
感谢~

**Comment by raoenhui** [comment]
我也不确定怎么生成的，看提交记录是Update Avocode image ，可能用 Avocode 生成的，我已经xiangTim提了这个问题， https://github.com/zeit/next-site/pull/20
![image](https://user-images.githubusercontent.com/14011130/75741855-d45a4100-5d46-11ea-8412-75ecc020e724.png)

**Comment by keithMonster** [comment]
好的，谢谢。

**Comment by raoenhui** [comment]
"I have found the answer in the README file",readme 好像没有说具体怎么生成svg，你找到是怎么生成呢？

**Comment by raoenhui** [comment]
> 好的，谢谢。

"I have found the answer in the README file",readme 好像没有说具体怎么生成svg，你找到是怎么生成呢？
